"""Stable, user-safe K-Slide errors."""

from __future__ import annotations

from dataclasses import dataclass, field
from enum import Enum
from typing import Any


class ErrorCode(str, Enum):
    INPUT_NOT_FOUND = "KSLIDE_INPUT_NOT_FOUND"
    INPUT_UNSUPPORTED = "KSLIDE_INPUT_UNSUPPORTED"
    INPUT_CORRUPT = "KSLIDE_INPUT_CORRUPT"
    INPUT_EMPTY = "KSLIDE_INPUT_EMPTY"
    INPUT_TYPE_MISMATCH = "KSLIDE_INPUT_TYPE_MISMATCH"
    INPUT_TOO_LARGE = "KSLIDE_INPUT_TOO_LARGE"
    INPUT_ARCHIVE_UNSAFE = "KSLIDE_INPUT_ARCHIVE_UNSAFE"
    PATH_OUTSIDE_ALLOWED_ROOT = "KSLIDE_PATH_OUTSIDE_ALLOWED_ROOT"
    RUN_NOT_FOUND = "KSLIDE_RUN_NOT_FOUND"
    STATE_CORRUPT = "KSLIDE_STATE_CORRUPT"
    INVALID_TRANSITION = "KSLIDE_INVALID_STATE_TRANSITION"
    SCHEMA_INVALID = "KSLIDE_SCHEMA_INVALID"
    CONFIG_INVALID = "KSLIDE_CONFIG_INVALID"
    AUTHENTICATION_FAILED = "KSLIDE_AUTHENTICATION_FAILED"
    VERIFICATION_FAILED = "KSLIDE_VERIFICATION_FAILED"
    COMPLETION_BLOCKED = "KSLIDE_COMPLETION_BLOCKED"
    INSTALL_COLLISION = "KSLIDE_INSTALL_COLLISION"
    INSTALL_INVALID = "KSLIDE_INSTALL_INVALID"
    RUNTIME_UNKNOWN = "KSLIDE_RUNTIME_UNKNOWN"
    MODEL_UNKNOWN = "KSLIDE_MODEL_UNKNOWN"
    PDF_RENDER_UNAVAILABLE = "KSLIDE_PDF_RENDER_UNAVAILABLE"
    PPTX_RENDER_UNAVAILABLE = "KSLIDE_PPTX_RENDER_UNAVAILABLE"
    OCR_UNAVAILABLE = "KSLIDE_OCR_UNAVAILABLE"
    OCR_PROVIDER_UNAVAILABLE = "KSLIDE_OCR_PROVIDER_UNAVAILABLE"
    CLASSIFICATION_POLICY_INVALID = "KSLIDE_CLASSIFICATION_POLICY_INVALID"
    CLASSIFICATION_POLICY_ROUTE_MISMATCH = "KSLIDE_CLASSIFICATION_POLICY_ROUTE_MISMATCH"
    CLASSIFICATION_POLICY_IDENTITY_MISMATCH = "KSLIDE_CLASSIFICATION_POLICY_IDENTITY_MISMATCH"
    CLASSIFICATION_UNKNOWN = "KSLIDE_CLASSIFICATION_UNKNOWN"
    CLASSIFICATION_NOT_APPROVED = "KSLIDE_CLASSIFICATION_NOT_APPROVED"
    EGRESS_POLICY_INVALID = "KSLIDE_EGRESS_POLICY_INVALID"
    EGRESS_CAPABILITY_DENIED = "KSLIDE_EGRESS_CAPABILITY_DENIED"
    EGRESS_ROUTE_MISMATCH = "KSLIDE_EGRESS_ROUTE_MISMATCH"
    OPENCODE_BOOTSTRAP_INVALID = "KSLIDE_OPENCODE_BOOTSTRAP_INVALID"
    STALE_EVIDENCE = "KSLIDE_STALE_EVIDENCE"
    UNKNOWN_REGION = "KSLIDE_UNKNOWN_REGION"
    UNKNOWN_TABLE = "KSLIDE_UNKNOWN_TABLE"
    UNKNOWN_TABLE_CELL = "KSLIDE_UNKNOWN_TABLE_CELL"
    UNKNOWN_SOURCE_ELEMENT = "KSLIDE_UNKNOWN_SOURCE_ELEMENT"
    UNKNOWN_WORK_UNIT = "KSLIDE_UNKNOWN_WORK_UNIT"
    WORK_UNIT_CONFLICT = "KSLIDE_WORK_UNIT_CONFLICT"
    WORK_UNIT_ALREADY_COMPLETE = "KSLIDE_WORK_UNIT_ALREADY_COMPLETE"
    EVIDENCE_INCOMPLETE = "KSLIDE_EVIDENCE_INCOMPLETE"
    NORMALIZATION_FAILED = "KSLIDE_NORMALIZATION_FAILED"
    IMAGE_DECODE_FAILED = "KSLIDE_IMAGE_DECODE_FAILED"
    PDF_ENCRYPTED = "KSLIDE_PDF_ENCRYPTED"
    PPTX_CONVERSION_TIMEOUT = "KSLIDE_PPTX_CONVERSION_TIMEOUT"
    RENDER_COUNT_MISMATCH = "KSLIDE_RENDER_COUNT_MISMATCH"
    DUPLICATE_WORK_UNIT_ID = "KSLIDE_DUPLICATE_WORK_UNIT_ID"
    DUPLICATE_DOCUMENT_ID = "KSLIDE_DUPLICATE_DOCUMENT_ID"
    DUPLICATE_SOURCE_ID = "KSLIDE_DUPLICATE_SOURCE_ID"
    NUMERIC_MISMATCH = "KSLIDE_NUMERIC_MISMATCH"
    MODALITY_MISMATCH = "KSLIDE_MODALITY_MISMATCH"
    CLAIM_UNSUPPORTED = "KSLIDE_CLAIM_UNSUPPORTED"
    INSTALL_LOCAL_MODIFICATION = "KSLIDE_INSTALL_LOCAL_MODIFICATION"
    RESOURCE_LIMIT = "KSLIDE_RESOURCE_LIMIT"
    RETENTION_INVALID = "KSLIDE_RETENTION_INVALID"
    RETENTION_REFUSED = "KSLIDE_RETENTION_REFUSED"
    DELETION_INVALID = "KSLIDE_DELETION_INVALID"
    DELETION_BLOCKED = "KSLIDE_DELETION_BLOCKED"
    DELETION_PARTIAL = "KSLIDE_DELETION_PARTIAL"
    DELETION_TARGET_FAILED = "KSLIDE_DELETION_TARGET_FAILED"
    DELETION_TARGET_CHANGED = "KSLIDE_DELETION_TARGET_CHANGED"
    LEGAL_HOLD_BLOCKED = "KSLIDE_LEGAL_HOLD_BLOCKED"
    LEGAL_HOLD_UNKNOWN = "KSLIDE_LEGAL_HOLD_UNKNOWN"
    PRODUCTION_PROFILE_INVALID = "KSLIDE_PRODUCTION_PROFILE_INVALID"
    SUPPORT_BUNDLE_INVALID = "KSLIDE_SUPPORT_BUNDLE_INVALID"
    EXECUTION_NOT_FOUND = "KSLIDE_EXECUTION_NOT_FOUND"
    EXECUTION_CONFLICT = "KSLIDE_EXECUTION_CONFLICT"
    EXECUTION_STALE = "KSLIDE_EXECUTION_STALE"
    EXECUTION_UNSUPPORTED_VERSION = "KSLIDE_EXECUTION_UNSUPPORTED_VERSION"
    EXECUTION_INVALID = "KSLIDE_EXECUTION_INVALID"
    EXECUTION_ENVIRONMENT_MISMATCH = "KSLIDE_EXECUTION_ENVIRONMENT_MISMATCH"
    EXECUTION_AUTHORIZATION_REQUIRED = "KSLIDE_EXECUTION_AUTHORIZATION_REQUIRED"
    INTERNAL = "KSLIDE_INTERNAL"


@dataclass
class KSlideError(Exception):
    """An error that can be shown without exposing raw internals."""

    code: ErrorCode
    message: str
    details: dict[str, Any] = field(default_factory=dict)

    def __post_init__(self) -> None:
        super().__init__(self.message)

    def as_dict(self) -> dict[str, Any]:
        # Error dictionaries are operational data and may cross the CLI or
        # OpenCode boundary. Keep the source/evidence payloads separate; only
        # this diagnostic representation is sanitized.
        from .redaction import sanitize_operational

        return sanitize_operational({"code": self.code.value, "message": self.message, "details": self.details})
